const fs = require('fs'), path = require('path');
const files = {
  'package.json': JSON.stringify({ name: "luokai-garden", private: true, type: "module", scripts: { "build": "nuxt build", "dev": "nuxt dev", "db:push": "prisma db push", "db:seed": "tsx prisma/seed.ts" }, dependencies: { "@prisma/client": "^5.20.0", "@vueuse/core": "^11.1.0", "bcryptjs": "^2.4.3", "class-variance-authority": "^0.7.0", "clsx": "^2.1.1", "dayjs": "^1.11.13", "jsonwebtoken": "^9.0.2", "lucide-vue-next": "^0.453.0", "markdown-it": "^14.1.0", "markdown-it-anchor": "^9.2.0", "prisma": "^5.20.0", "shiki": "^1.22.2", "tailwind-merge": "^2.5.4", "zod": "^3.23.8" }, devDependencies: { "@nuxtjs/color-mode": "^3.5.0", "@nuxtjs/tailwindcss": "^6.12.2", "@types/node": "^20.17.0", "nuxt": "^3.13.2", "tailwindcss": "^3.4.14", "tsx": "^4.19.1", "typescript": "^5.6.3", "vue": "^3.5.12" } }, null, 2),
  'nuxt.config.ts': `export default defineNuxtConfig({ compatibilityDate: '2024-04-03', modules: ['@nuxtjs/tailwindcss', '@nuxtjs/color-mode', '@vueuse/nuxt'], colorMode: { classSuffix: '', preference: 'system' }, css: ['~/assets/css/main.css'] })`,
  'tailwind.config.ts': `export default { darkMode: 'class', content: ['./components/**/*.{js,vue,ts}', './layouts/**/*.vue', './pages/**/*.vue', './app.vue'], theme: { extend: { colors: { brand: { 50: '#f0fdf4', 500: '#22c55e', 600: '#16a34a' } } } } }`,
  'assets/css/main.css': `@tailwind base;\n@tailwind components;\n@tailwind utilities;\nbody { @apply bg-zinc-50 text-zinc-900 dark:bg-zinc-950 dark:text-zinc-100 antialiased; }`,
  '.env': `DATABASE_URL="mysql://root:LuokaiAdmin2025!@localhost:3306/luokai_blog?schema=public"\nJWT_SECRET="luokai-garden-secret-key-2025"`,
  'prisma/schema.prisma': `datasource db { provider = "mysql" url = env("DATABASE_URL") }\ngenerator client { provider = "prisma-client-js" }\nmodel User { id Int @id @default(autoincrement()) \n username String @unique \n passwordHash String @map("password_hash") \n nickname String @default("洛凯") \n role String @default("admin") \n createdAt DateTime @default(now()) \n articles Article[] \n essays Essay[] \n @@map("users") }\nmodel Article { id Int @id @default(autoincrement()) \n slug String @unique \n title String \n summary String \n content String @db.LongText \n isPublished Boolean @default(true) \n views Int @default(0) \n readingTime Int @default(3) \n authorId Int \n author User @relation(fields: [authorId], references: [id]) \n createdAt DateTime @default(now()) \n @@map("articles") }\nmodel Essay { id Int @id @default(autoincrement()) \n content String @db.Text \n mood String? \n weather String? \n likes Int @default(0) \n isPublished Boolean @default(true) \n authorId Int \n author User @relation(fields: [authorId], references: [id]) \n createdAt DateTime @default(now()) \n @@map("essays") }`,
  'app.vue': `<template><NuxtLayout><NuxtPage /></NuxtLayout></template>`,
  'layouts/default.vue': `<script setup lang="ts">\nimport { Sparkles, BookOpen, Feather, User } from 'lucide-vue-next'\n</script>\n<template><div class="min-h-screen flex flex-col max-w-5xl mx-auto px-4"><header class="h-16 flex items-center justify-between border-b border-zinc-200 dark:border-zinc-800"><NuxtLink to="/" class="font-bold flex items-center gap-2">🌸 <span>洛凯花园</span></NuxtLink><nav class="flex gap-4 text-sm font-medium"><NuxtLink to="/">首页</NuxtLink><NuxtLink to="/articles">文章</NuxtLink><NuxtLink to="/essays">随笔</NuxtLink><NuxtLink to="/about">关于</NuxtLink></nav></header><main class="flex-1 py-8"><slot /></main><footer class="py-6 border-t border-zinc-200 dark:border-zinc-800 text-xs text-zinc-400 text-center">© 2025 洛凯花园 · Powered by Nuxt 3</footer></div></template>`,
  'pages/index.vue': `<template><div class="space-y-8"><section class="py-8 space-y-4 max-w-2xl"><div class="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-medium bg-emerald-50 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-300">🌸 Digital Garden · 持续耕作中</div><h1 class="text-4xl font-extrabold tracking-tight">你好，我是 <span class="text-emerald-600">洛凯</span> 🌿</h1><p class="text-zinc-600 dark:text-zinc-400">欢迎来到「洛凯花园」。这里是我记录技术探索、架构沉淀与碎片随想的一方数字空间。</p><div class="flex gap-3 pt-2"><NuxtLink to="/articles" class="px-4 py-2 rounded-xl text-sm font-medium bg-emerald-600 text-white shadow-md">阅读文章</NuxtLink><NuxtLink to="/essays" class="px-4 py-2 rounded-xl text-sm font-medium border border-zinc-200 dark:border-zinc-800">随笔时间轴</NuxtLink></div></section></div></template>`,
  'pages/articles/index.vue': `<template><div class="space-y-6"><h1 class="text-2xl font-bold">深度长文</h1><p class="text-xs text-zinc-400">系统沉淀前端设计系统、Nuxt 3 全栈架构与开发实践</p></div></template>`,
  'pages/essays/index.vue': `<template><div class="space-y-6"><h1 class="text-2xl font-bold">随笔花絮</h1><p class="text-xs text-zinc-400">即刻时间轴 · 灵感与碎片的生长记录</p></div></template>`,
  'pages/about.vue': `<template><div class="space-y-6 max-w-2xl"><h1 class="text-2xl font-bold">关于洛凯花园</h1><p class="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed">基于 Nuxt 3 + Tailwind CSS + MySQL 构建的个人数字花园。</p></div></template>`
};
for (const [f, c] of Object.entries(files)) { const p = path.join(__dirname, f); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, c.trim(), 'utf8'); }
console.log('🎉 「洛凯花园」全套工程文件已在 D:\\luo_kai_blog 落地完成！');