// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/v1/articles/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/articles/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/articles/[id].put').default>>>>
    }
    '/api/v1/articles/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/articles/[slug].get').default>>>>
    }
    '/api/v1/articles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/articles/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/articles/index.post').default>>>>
    }
    '/api/v1/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/auth/login.post').default>>>>
    }
    '/api/v1/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/auth/me.get').default>>>>
    }
    '/api/v1/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/auth/register.post').default>>>>
    }
    '/api/v1/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/categories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/categories/index.post').default>>>>
    }
    '/api/v1/comments/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/comments/[id].delete').default>>>>
    }
    '/api/v1/comments/:id/approve': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/comments/[id]/approve.patch').default>>>>
    }
    '/api/v1/comments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/comments/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/comments/index.post').default>>>>
    }
    '/api/v1/essays/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/essays/[id].delete').default>>>>
    }
    '/api/v1/essays/:id/like': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/essays/[id]/like.post').default>>>>
    }
    '/api/v1/essays': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/essays/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/essays/index.post').default>>>>
    }
    '/api/v1/notebooks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/notebooks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/notebooks/index.post').default>>>>
    }
    '/api/v1/notes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/notes/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/notes/[id].put').default>>>>
    }
    '/api/v1/notes/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/notes/[slug].get').default>>>>
    }
    '/api/v1/notes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/notes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/notes/index.post').default>>>>
    }
    '/api/v1/notes/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/notes/sync.post').default>>>>
    }
    '/api/v1/notes/sync/assets': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/notes/sync/assets.post').default>>>>
    }
    '/api/v1/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/search/index.get').default>>>>
    }
    '/api/v1/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/settings/index.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/settings/index.patch').default>>>>
    }
    '/api/v1/stats/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/stats/overview.get').default>>>>
    }
    '/api/v1/tags': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/tags/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/tags/index.post').default>>>>
    }
    '/api/v1/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/upload.post').default>>>>
    }
    '/api/v1/uploads/sign': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/api/v1/uploads/sign.post').default>>>>
    }
    '/database-er-diagram.svg': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/routes/database-er-diagram.svg').default>>>>
    }
    '/feed.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/routes/feed.xml').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/routes/sitemap.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../.pnpm/@nuxt+nitro-server@3.21.11_db0@0.3.4_esbuild@0.28.2_ioredis@5.11.1_supports-color@10.0._2eb6b3b4ee261884245b2d4558507643/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}