// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../.pnpm/nuxt@3.21.11_@oxc-project+types@0.143.0_@types+node@20.19.43_@vue+compiler-sfc@3.5.41_c_18cbc041533af932bcb03e20deddf35b/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../.pnpm/nuxt@3.21.11_@oxc-project+types@0.143.0_@types+node@20.19.43_@vue+compiler-sfc@3.5.41_c_18cbc041533af932bcb03e20deddf35b/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../.pnpm/nuxt@3.21.11_@oxc-project+types@0.143.0_@types+node@20.19.43_@vue+compiler-sfc@3.5.41_c_18cbc041533af932bcb03e20deddf35b/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../.pnpm/nuxt@3.21.11_@oxc-project+types@0.143.0_@types+node@20.19.43_@vue+compiler-sfc@3.5.41_c_18cbc041533af932bcb03e20deddf35b/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../.pnpm/nuxt@3.21.11_@oxc-project+types@0.143.0_@types+node@20.19.43_@vue+compiler-sfc@3.5.41_c_18cbc041533af932bcb03e20deddf35b/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../.pnpm/nuxt@3.21.11_@oxc-project+types@0.143.0_@types+node@20.19.43_@vue+compiler-sfc@3.5.41_c_18cbc041533af932bcb03e20deddf35b/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../.pnpm/nuxt@3.21.11_@oxc-project+types@0.143.0_@types+node@20.19.43_@vue+compiler-sfc@3.5.41_c_18cbc041533af932bcb03e20deddf35b/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../.pnpm/nuxt@3.21.11_@oxc-project+types@0.143.0_@types+node@20.19.43_@vue+compiler-sfc@3.5.41_c_18cbc041533af932bcb03e20deddf35b/node_modules/nuxt/dist/app/plugins/island-link-navigation.client.js")> &
  InjectionType<typeof import("../../../../.pnpm/nuxt@3.21.11_@oxc-project+types@0.143.0_@types+node@20.19.43_@vue+compiler-sfc@3.5.41_c_18cbc041533af932bcb03e20deddf35b/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../.pnpm/@vueuse+motion@3.0.3_magicast@0.5.4_vue@3.5.41_typescript@5.6.3_/node_modules/@vueuse/motion/dist/nuxt/runtime/templates/motion.js")> &
  InjectionType<typeof import("../../../../.pnpm/@nuxtjs+color-mode@3.5.0_magicast@0.5.4/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../../../.pnpm/@nuxtjs+color-mode@3.5.0_magicast@0.5.4/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:island-link-navigation' | 'nuxt:global-components' | 'nuxt:prefetch'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
