// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/12/2026, 10:59:42 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../../../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/li/workspace/mystic-garden/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/li/workspace/mystic-garden/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/li/workspace/mystic-garden/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/li/workspace/mystic-garden/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/li/workspace/mystic-garden/app/plugins/**/*.{js,ts,mjs}","/home/li/workspace/mystic-garden/app/composables/**/*.{js,ts,mjs}","/home/li/workspace/mystic-garden/app/utils/**/*.{js,ts,mjs}","/home/li/workspace/mystic-garden/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/li/workspace/mystic-garden/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/li/workspace/mystic-garden/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/li/workspace/mystic-garden/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;